<!DOCTYPE html>



  


<html class="theme-next muse use-motion" lang="zh-Hans">
<head>
  <meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<meta name="theme-color" content="#222">









<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
















  
  
  <link href="/blog/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css" />







<link href="/blog/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css" />

<link href="/blog/css/main.css?v=5.1.4" rel="stylesheet" type="text/css" />


  <link rel="apple-touch-icon" sizes="180x180" href="/blog/images/apple-touch-icon-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="32x32" href="/blog/images/favicon-32x32-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="16x16" href="/blog/images/favicon-16x16-next.png?v=5.1.4">


  <link rel="mask-icon" href="/blog/images/logo.svg?v=5.1.4" color="#222">





  <meta name="keywords" content="Node.js," />










<meta name="description" content="转自：http://www.infoq.com/cn/articles/quit-scheme-of-node-uncaughtexception-emergence&amp;nbsp;Node 的异步特性是它最大的魅力，但是在带来便利的同时也带来了不少麻烦和坑，错误捕获就是一个。由于 Node 的异步特性，导致我们无法使用 try/catch 来捕获回调函数中的异常，例如:try {    consol">
<meta name="keywords" content="Node.js">
<meta property="og:type" content="article">
<meta property="og:title" content="Node 出现 uncaughtException 之后的优雅退出方案">
<meta property="og:url" content="https://vanessa.js.org/blog/cjcujziry00epxwrqa3iykorb/index.html">
<meta property="og:site_name" content="Vanessa">
<meta property="og:description" content="转自：http://www.infoq.com/cn/articles/quit-scheme-of-node-uncaughtexception-emergence&amp;nbsp;Node 的异步特性是它最大的魅力，但是在带来便利的同时也带来了不少麻烦和坑，错误捕获就是一个。由于 Node 的异步特性，导致我们无法使用 try/catch 来捕获回调函数中的异常，例如:try {    consol">
<meta property="og:locale" content="zh-Hans">
<meta property="og:updated_time" content="2018-01-25T13:29:19.000Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Node 出现 uncaughtException 之后的优雅退出方案">
<meta name="twitter:description" content="转自：http://www.infoq.com/cn/articles/quit-scheme-of-node-uncaughtexception-emergence&amp;nbsp;Node 的异步特性是它最大的魅力，但是在带来便利的同时也带来了不少麻烦和坑，错误捕获就是一个。由于 Node 的异步特性，导致我们无法使用 try/catch 来捕获回调函数中的异常，例如:try {    consol">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/blog/',
    scheme: 'Muse',
    version: '5.1.4',
    sidebar: {"position":"left","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
    fancybox: true,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>



  <link rel="canonical" href="https://vanessa.js.org/blog/cjcujziry00epxwrqa3iykorb/"/>





  <title>Node 出现 uncaughtException 之后的优雅退出方案 | Vanessa</title>
  








</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-Hans">

  
  
    
  

  <div class="container sidebar-position-left page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/blog/"  class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">Vanessa</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
      
        <p class="site-subtitle"></p>
      
  </div>

  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/blog/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br />
            
            首页
          </a>
        </li>
      
        
        <li class="menu-item menu-item-archives">
          <a href="/blog/archives/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br />
            
            归档
          </a>
        </li>
      

      
    </ul>
  

  
</nav>



 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  <article class="post post-type-normal" itemscope itemtype="http://schema.org/Article">
  
  
  
  <div class="post-block">
    <link itemprop="mainEntityOfPage" href="https://vanessa.js.org/blog/blog/cjcujziry00epxwrqa3iykorb/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="name" content="Vanessa">
      <meta itemprop="description" content="">
      <meta itemprop="image" content="/blog/images/avatar.gif">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Vanessa">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">Node 出现 uncaughtException 之后的优雅退出方案</h1>
        

        <div class="post-meta">
          <span class="post-time">
            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">发表于</span>
              
              <time title="创建于" itemprop="dateCreated datePublished" datetime="2014-02-26T14:34:27+08:00">
                2014-02-26
              </time>
            

            

            
          </span>

          

          
            
          

          
          

          

          

          

        </div>
      </header>
    

    
    
    
    <div class="post-body" itemprop="articleBody">

      
      

      
        <p>转自：<a href="http://www.infoq.com/cn/articles/quit-scheme-of-node-uncaughtexception-emergence" target="_blank" rel="noopener">http://www.infoq.com/cn/articles/quit-scheme-of-node-uncaughtexception-emergence</a></p><br><p>&nbsp;</p><br><p>Node 的异步特性是它最大的魅力，但是在带来便利的同时也带来了不少麻烦和坑，错误捕获就是一个。由于 Node 的异步特性，导致我们无法使用 try/catch 来捕获回调函数中的异常，例如:</p><br><pre class="brush: js">try {<br>    console.log(‘进入 try/catch’);<br>    require(‘fs’).stat(‘SOME_FILE_DOES_NOT_EXIST’,<br>function readCallback(err, content) {<br>        if (err) {<br>            throw err; // 抛出异常<br>        }<br>    });<br>} catch (e) {<br>    // 这里捕获不到 readCallback 函数中抛出的异常<br>} finally {<br>    console.log(‘离开 try/catch’);<br>}</pre><br><p>运行结果是:</p><br><pre class="brush: js">进入 try/catch<br>离开 try/catch<br><br>test.js:7<br>            throw err; // 抛出异常<br>                  ^<br>Error: ENOENT, stat ‘SOME_FILE_DOES_NOT_EXIST’</pre><br><p>上面代码中由于 <code>fs.stat</code> 去查询一个不存在的文件的状态，导致 <code>readCallback</code> 抛出了一个异常。由于 <code>fs.read</code> 的异步特性，<code>readCallback</code> 函数的调用发生在 <code>try/catch</code> 块结束之后，所以该异常不会被 try/catch 捕获。之后 Node 会触发 <code>uncaughtException</code> 事件，如果这个事件依然没有得到响应，整个进程(<code>process</code>)就会 crash。</p><br><p>程序员永远无法保证代码中不出现 <code>uncaughtException</code>，即便是自己代码写的足够小心，也不能保证用的第三方模块没有 bug，例如:</p><br><pre class="brush: js">var deserialize = require(‘deserialize’);<br>// 假设 deserialize 是一个带有 bug 的第三方模块<br><br>// app 是一个 express 服务对象<br>app.get(‘/users’, function (req, res) {<br>    mysql.query(‘SELECT <em> FROM user WHERE id=1’, function (err, user) {<br>        var config = deserialize(user.config);<br>// 假如这里触发了 deserialize 的 bug<br>        res.send(config);<br>    });<br>});</em></pre><br><p>如果不幸触发了 <code>deserialize</code> 模块的 bug，这里就会抛出一个异常，最终结果是整个服务 crash。</p><br><p>当这种情况发生在 Web 服务上时结果是灾难性的。<code>uncaughtException</code> 错误会导致当前的所有的用户连接都被中断，甚至不能返回一个正常的 HTTP 错误码，用户只能等到浏览器超时才能看到一个 <code>no data received</code> 错误。</p><br><p>这是一种非常野蛮粗暴的异常处理机制，任何线上服务都不应该因为 <code>uncaughtException</code> 导致服务器崩溃。一个友好的错误处理机制应该满足三个条件:</p><br><ol><br><li>对于引发异常的用户，返回 500 页面</li><br><li>其他用户不受影响，可以正常访问</li><br><li>不影响整个进程的正常运行</li><br></ol><br><p>很遗憾的是，保证 <code>uncaughtException</code> 不影响整个进程的健康运转是不可能的。当 Node 抛出 <code>uncaughtException</code> 异常时就会丢失当前环境的堆栈，导致 Node 不能正常进行内存回收。也就是说，每一次 <code>uncaughtException</code> 都有可能导致内存泄露。</p><br><p>既然如此，退而求其次，我们可以在满足前两个条件的情况下退出进程以便重启服务。</p><br><h2>用 domain 来捕获异步异常</h2><br><p>普遍的思路是，如果可以通过某种方式来捕获回调函数中的异常，那么就不会有 <code>uncaughtException</code> 错误导致的崩溃。为了解决这个问题，Node 0.8 之后的版本新增了 <code>domain</code> 模块，它可以用来捕获回调函数中抛出的异常。</p><br><p><code>domain</code> 主要的 API 有 <code>domain.run</code> 和 <code>error</code> 事件。简单的说，通过 <code>domain.run</code> 执行的函数中引发的异常都可以通过 <code>domain</code> 的 <code>error</code> 事件捕获，例如:</p><br><pre class="brush: js">var domain = require(‘domain’);<br>var d = domain.create();<br>d.run(function () {<br>    setTimeout(function () {<br>        throw new Error(‘async error’); // 抛出一个异步异常<br>    }, 1000);<br>});<br><br>d.on(‘error’, function (err) {<br>    console.log(‘catch err:’, err); // 这里可以捕获异步异常<br>});</pre><br><p>通过 <code>domain</code> 模块，以及 JavaScript 的词法作用域特性，可以很轻易的为引发异常的用户返回 500 页面。以 express 为例:</p><br><pre class="brush: js">var app = express();<br>var server = require(‘http’).createServer(app);<br>var domain = require(‘domain’);<br><br>app.use(function (req, res, next) {<br>    var reqDomain = domain.create();<br>    reqDomain.on(‘error’, function (err) { // 下面抛出的异常在这里被捕获<br>        res.send(500, err.stack); // 成功给用户返回了 500<br>    });<br><br>    reqDomain.run(next);<br>});<br><br>app.get(‘/‘, function () {<br>    setTimeout(function () {<br>        throw new Error(‘async exception’); // 抛出一个异步异常<br>    }, 1000);<br>});</pre><br><p>上面的代码将 domain 作为一个中间件来使用，保证之后 express 所有的中间件都在 <code>domain.run</code> 函数内部执行。这些中间件内的异常都可以通过 <code>error</code> 事件来捕获。</p><br><p>尽管借助于闭包，我们可以正常的给用户返回 500 错误，但是 <code>domain</code> 捕获到错误时依然会丢失堆栈信息，此时已经无法保证程序的健康运行，必须退出。Node http server 提供了 <code>close</code> 方法，该方法在调用时会停止 server 接收新的请求，但不会断开当前已经建立的连接。</p><br><pre class="brush: js">reqDomain.on(‘error’, function () {<br>    try {<br>        // 强制退出机制<br>        var killTimer = setTimeout(function () {<br>            process.exit(1);<br>        }, 30000);<br>        killTimer.unref(); // 非常重要<br><br>        // 自动退出机制，停止接收新链接，等待当前已建立连接的关闭<br>        server.close(function () {<br>       // 此时所有连接均已关闭，此时 Node 会自动退出，不需要再调用<br>process.exit(1) 来结束进程<br>        });<br>    } catch(e) {<br>        console.log(‘err’, e.stack);<br>    }<br>});</pre><br><p>这个例子来自 Node 的文档。其中有几个关键点：</p><br><ul><br><li>Node 有个非常好的特性，所有连接都被释放后进程会自动结束，所以不需要再 <code>server.close</code> 方法的回调函数中退出进程</li><br><li>强制退出机制: 因为用户连接有可能因为某些原因无法释放，在这种情况下应该强制退出整个进程。</li><br><li><code>killTimer.unref()</code>: 如果不使用 <code>unref</code> 方法，那么即使 server 的所有连接都关闭，Node 也会保持运行直到 <code>killTimer</code> 的回调函数被调用。<code>unref</code> 可以创建一个”不保持程序运行”的计时器。</li><br><li>处理异常时要小心的把异常处理逻辑用 try/catch 包住，避免处理异常时抛出新的异常</li><br></ul><br><p>通过 <code>domain</code> 似乎就已经解决了我们的需求: 给触发异常的用户一个 500，停止接收新请求，提供正常的服务给已经建立连接的用户，直到所有请求都已结束，退出进程。但是，理想很丰满，现实很骨感，<code>domain</code> 有个最大的问题，它<a href="http://cnodejs.org/topic/516b64596d38277306407936" target="_blank" rel="noopener">不能捕获所有的异步异常</a>！。也就是说，即使用了 <code>domain</code>，程序依然有因为 <code>uncaughtException</code> crash 的可能。</p><br><p>所幸的是我们可以监听 <code>uncaughtException</code> 事件。</p><br><h2><code>uncaughtException</code> 事件</h2><br><p><code>uncaughtException</code> 是一个非常古老的事件。当 Node 发现一个未捕获的异常时，会触发这个事件。并且如果这个事件存在回调函数，Node 就不会强制结束进程。这个特性，可以用来弥补 <code>domain</code> 的不足:</p><br><pre class="brush: js">process.on(‘uncaughtException’, function (err) {<br>    console.log(err);<br><br>    try {<br>        var killTimer = setTimeout(function () {<br>            process.exit(1);<br>        }, 30000);<br>        killTimer.unref();<br><br>        server.close();<br>    } catch (e) {<br>        console.log(‘error when exit’, e.stack);<br>    }<br>});</pre><br><p><code>uncaughtException</code> 事件的缺点在于无法为抛出异常的用户请求返回一个 500 错误，这是由于 <code>uncaughtException</code> 丢失了当前环境的上下文，比如下面的例子就是它做不到的:</p><br><pre class="brush: js">javascript<br>app.get(‘/‘, function (req, res) {<br>    setTimeout(function () {<br>        throw new Error(‘async error’);<br>// uncaughtException, 导致 req 的引用丢失<br>        res.send(200);<br>    }, 1000);<br>});<br><br>process.on(‘uncaughtException’, function (err) {<br>    res.send(500); // 做不到，拿不到当前请求的 res 对象<br>});</pre><br><p>最终出错的用户只能等待浏览器超时。</p><br><h2><code>domain</code> + <code>uncaughtException</code></h2><br><p>所以，我们可以结合两种异常捕获机制，用 <code>domain</code> 来捕获大部分的异常，并且提供友好的 500 页面以及优雅退出。对于剩下的异常，通过 <code>uncaughtException</code> 事件来避免服务器直接 crash。</p><br><p>代码如下:</p><br><pre class="brush: js">var app = express();<br>var server = require(‘http’).create(app);<br>var domain = require(‘domain’);<br><br>// 使用 domain 来捕获大部分异常<br>app.use(function (req, res, next) {<br>    var reqDomain = domain.create();<br>    reqDomain.on(‘error’, function () {<br>        try {<br>            var killTimer = setTimeout(function () {<br>                process.exit(1);<br>            }, 30000);<br>            killTimer.unref();<br><br>            server.close();<br><br>            res.send(500);<br>        } catch (e) {<br>            console.log(‘error when exit’, e.stack);<br>        }<br>    });<br><br>    reqDomain.run(next);<br>});<br><br>// uncaughtException 避免程序崩溃<br>process.on(‘uncaughtException’, function (err) {<br>    console.log(err);<br><br>    try {<br>        var killTimer = setTimeout(function () {<br>            process.exit(1);<br>        }, 30000);<br>        killTimer.unref();<br><br>        server.close();<br>    } catch (e) {<br>        console.log(‘error when exit’, e.stack);<br>    }<br>});</pre><br><h2>其他的一些问题</h2><br><h3><code>express</code> 中异常的处理</h3><br><p>使用 <code>express</code> 时记住一定不要在 controller 的异步回调中抛出异常，例如:</p><br><pre class="brush: js">app.get(‘/‘, function (req, res, next) { // 总是接收 next 参数<br>    mysql.query(‘SELECT  FROM users’, function (err, results) {<br>        // 不要这样做<br>        if (err) throw err;<br><br>        // 应该将 err 传递给 errorHandler 处理<br>        if (err) return next(err);<br>    });<br>});<br><br>app.use(function (err, req, res, next) {<br> // 带有四个参数的 middleware 专门用来处理异常<br>    res.render(500, err.stack);<br>});</pre><br><h3>和 cluster 一起使用</h3><br><p>cluster 是 node 自带的负载均衡模块，使用 cluster 模块可以方便的建立起一套 master/slave 服务。在使用 cluster 模块时，需要注意不仅需要调用 <code>server.close()</code> 来关闭连接，同时还需要调用 <code>cluster.worker.disconnect()</code> 通知 master 进程已停止服务:</p><br><pre class="brush: js">var cluster = require(‘cluster’);<br><br>process.on(‘uncaughtException’, function (err) {<br>    console.log(err);<br><br>    try {<br>        var killTimer = setTimeout(function () {<br>            process.exit(1);<br>        }, 30000);<br>        killTimer.unref();<br><br>        server.close();<br><br>        if (cluster.worker) {<br>            cluster.worker.disconnect();<br>        }<br>    } catch (e) {<br>        console.log(‘error when exit’, e.stack);<br>    }<br>});</pre><br><h3>不要通过 <code>uncaughtException</code> 来忽略错误</h3><br><p>当 <code>uncaughtException</code> 事件有一个以上的 <code>listener</code> 时，会阻止 Node 结束进程。因此就有一个广泛流传的做法是监听 <code>process</code> 的 <code>uncaughtException</code> 事件来阻止进程退出，这种做法有内存泄露的风险，所以千万不要这么做:</p><br><pre>javascript<br>process.on(‘uncaughtException’, function (err) { // 不要这么做<br>    console.log(err);<br>});</pre><br><h3>pm2 对于 <code>uncaughtException</code> 的额外处理</h3><br><p>如果你在用 pm2 0.7.1 之前的版本，那么要当心。pm2 有一个 bug，如果进程抛出了 <code>uncaughtException</code>，无论代码中是否捕获了这个事件，进程都会被 pm2 杀死。0.7.2 之后的 pm2 解决了这个问题。</p><br><h3>要小心 worker.disconnect()</h3><br><p>如果你在退出进程时希望可以发消息给监控服务器，并且还使用了 cluster，那么这个时候要特别小心，比如下面的代码:</p><br><pre class="brush: js">var udpLog = dgram.createSocket(‘udp4’);<br>var cluster = require(‘cluster’);<br><br>process.on(‘uncaughtException’, function (err) {<br>    udpLog.send(‘process ‘ + process.pid + ‘ down’,<br>/<em> … 一些发送 udp 消息的参数 …</em>/);<br><br>    server.close();<br>    cluster.worker.disconnect();<br>});</pre><br><p>这份代码就不能正常的将消息发送出去。因为 <code>udpLog.send</code> 是一个异步方法，真正发消息的操作发生在下一个事件循环中。而在真正的发送消息之前 <code>cluster.worker.disconnect()</code> 就已经执行了。<code>worker.disconnect()</code> 会在当前进程没有任何链接之后，杀掉整个进程，这种情况有可能发生在发送 log 数据之前，导致 log 数据发不出去。</p><br><p>一个解决方法是在 <code>udpLog.send</code> 方法发送完数据后再调用 <code>worker.disconnect</code>:</p><br><pre class="brush: js">var udpLog = dgram.createSocket(‘udp4’);<br>var cluster = require(‘cluster’);<br><br>process.on(‘uncaughtException’, function (err) {<br>    udpLog.send(‘process ‘ + process.pid + ‘ down’, /<em> …<br>一些发送 udp 消息的参数 …</em>/, function () {<br>        cluster.worker.disconnect();<br>    });<br><br>    server.close();<br><br>    // 保证 worker.disconnect 不会拖太久..<br>    setTimeout(function () {<br>        cluster.worker.disconnect();<br>    }, 100).unref();<br>});</pre><br><h2>小节</h2><br><p>说了这么多，结论是，目前为止(Node 0.10.25)，依然没有一个完美的方案来解决任意异常的优雅退出问题。用 <code>domain</code> 来捕获大部分异常，并且通过 <code>uncaughtException</code> 避免程序 crash 是目前来说最理想的方案。回调异常的退出问题在遇到 cluster 以后会更加复杂，特别是对于连接关闭的处理要格外小心。</p><br><h2>参考文章</h2><br><ul><br><li><a href="http://nodejs.org/api/domain.html#domain_warning_don_t_ignore_errors" target="_blank" rel="noopener">Don’t ignore errors</a></li><br><li><a href="http://nodejs.org/api/domain.html" target="_blank" rel="noopener">Node API: domain</a></li><br><li><a href="http://nodejs.org/api/process.html" target="_blank" rel="noopener">Node API: process</a></li><br><li><a href="http://cnodejs.org/topic/516b64596d38277306407936" target="_blank" rel="noopener">Node.js 异步异常的处理与domain模块解析</a></li><br><li><a href="http://www.alloyteam.com/2013/12/node-js-series-exception-caught/" target="_blank" rel="noopener">Node.js异常捕获的一些实践</a></li><br></ul><br><hr><br><p>感谢<a href="http://www.infoq.com/cn/author/%E7%94%B0%E6%B0%B8%E5%BC%BA" target="_blank" rel="noopener">田永强</a>对本文的审校。</p><br><p>给InfoQ中文站投稿或者参与内容翻译工作，请邮件至<a href="mailto:editors@cn.infoq.com" target="_blank" rel="noopener">editors@cn.infoq.com</a>。也欢迎大家通过新浪微博（<a href="http://www.weibo.com/infoqchina" target="_blank" rel="noopener">@InfoQ</a>）或者腾讯微博（<a href="http://t.qq.com/infoqchina" target="_blank" rel="noopener">@InfoQ</a>）关注我们，并与我们的编辑和其他读者朋友交流。</p>
      
    </div>
    
    
    

    

    

    

    <footer class="post-footer">
      
        <div class="post-tags">
          
            <a href="/blog/tags/Node-js/" rel="tag"># Node.js</a>
          
        </div>
      

      
      
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/blog/cjcuj6cr9001zl6rqf9pycve7/" rel="next" title="10个最好的Node.js MVC框架">
                <i class="fa fa-chevron-left"></i> 10个最好的Node.js MVC框架
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/blog/cjcuj6j1s004ll6rqx87u2gqk/" rel="prev" title="2008 年总结">
                2008 年总结 <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
    </footer>
  </div>
  
  
  
  </article>



    <div class="post-spread">
      
    </div>
  </div>


          </div>
          


          

  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            站点概览
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <p class="site-author-name" itemprop="name">Vanessa</p>
              <p class="site-description motion-element" itemprop="description"></p>
          </div>

          <nav class="site-state motion-element">

            
              <div class="site-state-item site-state-posts">
              
                <a href="/blog/archives/">
              
                  <span class="site-state-item-count">874</span>
                  <span class="site-state-item-name">日志</span>
                </a>
              </div>
            

            

            
              
              
              <div class="site-state-item site-state-tags">
                
                  <span class="site-state-item-count">224</span>
                  <span class="site-state-item-name">标签</span>
                
              </div>
            

          </nav>

          

          

          
          

          
          

          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-2"><a class="nav-link" href="#undefined"><span class="nav-number">1.</span> <span class="nav-text">用 domain 来捕获异步异常</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#undefined"><span class="nav-number">2.</span> <span class="nav-text">uncaughtException 事件</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#undefined"><span class="nav-number">3.</span> <span class="nav-text">domain + uncaughtException</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#undefined"><span class="nav-number">4.</span> <span class="nav-text">其他的一些问题</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">4.1.</span> <span class="nav-text">express 中异常的处理</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">4.2.</span> <span class="nav-text">和 cluster 一起使用</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">4.3.</span> <span class="nav-text">不要通过 uncaughtException 来忽略错误</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">4.4.</span> <span class="nav-text">pm2 对于 uncaughtException 的额外处理</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">4.5.</span> <span class="nav-text">要小心 worker.disconnect()</span></a></li></ol></li><li class="nav-item nav-level-2"><a class="nav-link" href="#undefined"><span class="nav-number">5.</span> <span class="nav-text">小节</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#undefined"><span class="nav-number">6.</span> <span class="nav-text">参考文章</span></a></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; <span itemprop="copyrightYear">2018</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Vanessa</span>

  
</div>


  <div class="powered-by">由 <a class="theme-link" target="_blank" href="https://hexo.io">Hexo</a> 强力驱动</div>



  <span class="post-meta-divider">|</span>



  <div class="theme-info">主题 &mdash; <a class="theme-link" target="_blank" href="https://github.com/iissnan/hexo-theme-next">NexT.Muse</a> v5.1.4</div>




        







        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    

  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  












  
  
    <script type="text/javascript" src="/blog/lib/jquery/index.js?v=2.1.3"></script>
  

  
  
    <script type="text/javascript" src="/blog/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>
  

  
  
    <script type="text/javascript" src="/blog/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>
  

  
  
    <script type="text/javascript" src="/blog/lib/velocity/velocity.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/blog/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/blog/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
  


  


  <script type="text/javascript" src="/blog/js/src/utils.js?v=5.1.4"></script>

  <script type="text/javascript" src="/blog/js/src/motion.js?v=5.1.4"></script>



  
  

  
  <script type="text/javascript" src="/blog/js/src/scrollspy.js?v=5.1.4"></script>
<script type="text/javascript" src="/blog/js/src/post-details.js?v=5.1.4"></script>



  


  <script type="text/javascript" src="/blog/js/src/bootstrap.js?v=5.1.4"></script>



  


  




	





  





  












  





  

  

  

  
  

  

  

  

</body>
</html>
